### PR TITLE
Add currency symbol to configuration, keep using network name if not defined

### PR DESCRIPTION
**Pull request by alepc253**
### Feature

- [ ] Updated CHANGELOG.md
- [x] Is this a user submitted feature request?
  - [x] Link to issue: #807 
- [ ] Add test cases or procedure
- [x] Add PR label

### CODE REVIEW

**Comment by kvhnuke** [comment]
Lets create a symbol field in all network types and use that, I dont like doing this `const symbol = this.network.type.currencyName || this.network.type.name;`

it should be just `this.network.type.symbol`

**Comment by alepc253** [comment]
@kvhnuke and that `symbol` field should have set the same content as `name` by default, right?

**Comment by alepc253** [comment]
@kvhnuke I addressed your reviews, let me know if that works, thanks!

**Comment by kvhnuke** [comment]
@alepc253 Thank you, this looks good to me, @gamalielhere can you do a final check and see whether we replaced all the instances?

**Pull request merged**
