### PR TITLE
ui:  🎨  provider mentions

### PR DESCRIPTION
**Pull request by andrewdahn**
### UI
* \[x] Added entry to ./changelog
* \[x] Add PR label

### CODE REVIEW

**Comment by hsurf22** [comment]
Figma link
https://www.figma.com/file/Wcy6yS5uCtKfPvdAJVf4IK/Swap-Providers-(Handoff)?node-id=0%3A1

**Comment by hsurf22** [comment]
https://user-images.githubusercontent.com/9893774/133370342-ce87b70b-5ef2-4d3e-9605-cfbd82c2023c.mp4
Animation looks good, but the animation is little too short. Can you give it little bit of delay before it disappears?
Fade in fade out effect would be nice too. We have anime.js library, so feel free to use it if you want to. https://animejs.com/

**Review by hsurf22 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/9893774/133370342-ce87b70b-5ef2-4d3e-9605-cfbd82c2023c.mp4
Animation looks good, but the animation is little too short. Can you give it little bit of delay before it disappears?
Fade in fade out effect would be nice too. We have **anime.js** library, so feel free to use it if you want to. https://animejs.com/

**Review by hsurf22 — CHANGES_REQUESTED** [review]
Screenshot from 2021-09-14 22-06-37

The `<mew6-white-sheet>` default box-shadow looks too soft.
Can you add a prop to `<mew6-white-sheet>` to change box-shadow to
box-shadow: 0px 4px 4px rgb(11 40 64 / 4%), 0px 2px 10px rgb(11 40 64 / 6%), 0px 3px 16px rgb(11 40 64 / 4%);

**Comment by andrewdahn** [comment]
> Screenshot from 2021-09-14 22-06-37
> 
> The `<mew6-white-sheet>` default box-shadow looks too soft.
> Can you add a prop to `<mew6-white-sheet>` to change box-shadow to
> (This is from figma.)
> box-shadow: 0px 4px 4px rgb(11 40 64 / 4%), 0px 2px 10px rgb(11 40 64 / 6%), 0px 3px 16px rgb(11 40 64 / 4%);

Added new box shadow styling

**Review by hsurf22 — APPROVED** [review]

**Review by gamalielhere — APPROVED** [review]

**Pull request merged**
