### PR TITLE
Rename Aux to AuxComponent for Windows

### PR DESCRIPTION
**Pull request by wbobeirne**
The filename `AUX` (With any extension, any capitalization) is reserved in Windows. When you clone the repo, it omits the file, totally messing up the build. This just renames the Aux.tsx component file to AuxComponent.tsx. No other changes to code.

### CODE REVIEW

**Comment by dternyak** [comment]
Interesting, we're getting prettier conflicts here. Any ideas @james-prado?

**Comment by wbobeirne** [comment]
This is almost certainly because I committed this from Windows, and that probably didn't respect the commit hooks somehow.

**Comment by dternyak** [comment]
@wbobeirne I've pushed a commit that reformats those files with pre-commit - hopefully it's all fixed up after.

**Comment by dternyak** [comment]
Overall very interesting issue. Thanks for your time debugging this.

**Pull request merged**
