### PR TITLE
Devop/consolidate node prs

### PR DESCRIPTION
**Pull request by gamalielhere**
### Devop

- [x] Updated CHANGELOG.md
- [x] Add PR label
- [x] No hard-coded strings

### CODE REVIEW

**Comment by gamalielhere** [comment]
@zynecoin Removed your submitted node as the provided RPC returns a 403.

**Comment by gesseekur** [comment]
could you fix build so i can test :D

**Comment by zynecoin** [comment]
Hello our mainnet is under vpn now,we will open to public once you add our
network, should i give you vpn acces please?

Best,

Le mer. 17 juin 2020 à 19:47, Jessica Peng <notifications@github.com> a
écrit :

**Comment by zynecoin** [comment]
Hello,
You add zynecoin to this fetch ?

Best Regards,

Le mer. 17 juin 2020 à 21:40, Applinum <marketing.applinum@gmail.com> a
écrit :

**Pull request merged**
