### PR TITLE
Devop: 🔧 👷 Rootstock integration

### PR DESCRIPTION
**Pull request by ahsan-javaiid**
### Devop

* \[X] Added entry to ./changelog
* \[ ] Add PR label

### Description
This PR adds `Rootstock` network integration to MyEtherWallet. 
- Create or Import wallet with `Rootstock` is working
- Send / Receive `RBTC` and ERC20 tokens flow working
- Ledger connection and signing with `Rootstock` is working
- Rootstock name resolution is working

### Steps to test:
- Checkout to the branch in this PR
- `npm run dev` or `npm run juststart`
-  Now select `Rootstock` option to test items mentioned in the description section

### CODE REVIEW

**Comment by alepc253** [comment]
hey @gamalielhere, please take a look at this new PR for Rootstock (RSK)

**Comment by ahsan-javaiid** [comment]
Hi MEW Team: 👋

Users are eager to use Rootstock on MEW. It would be great if MEW team can consider this pull request. I would be happy to do any changes if required. 

cc: @gamalielhere @Abyscuit @kvhnuke @hsurf22

Rootstock plans to add couple more integration in MEW after this PR. So it would be great if this PR get considered.

**Comment by ahsan-javaiid** [comment]
Hi MEW team:

Updated the pull request and included checksum validation for `Rootstock` network. Give it a review or share thought's if need any changes. 

cc: @gamalielhere  @kvhnuke

**Comment by ahsan-javaiid** [comment]
Hi @gamalielhere

Just a reminder to consider/review this pull request: 🙏🏻
Thank you.

**Pull request merged**
