### PR TITLE
feat: Add Ethercluster by ETC Coop nodes

### PR DESCRIPTION
**Pull request by YazzyYaz**
### Feature

- [ ] Updated CHANGELOG.md
- [*] Is this a user submitted feature request?
  - [ ] Link to issue: This is updating ETC RPC endpoints to use those of Ethercluster which is supported by Ethereum Classic Cooperative. Commonwealth doesn't do work on ETC anymore, they work on Calisto.
- [ ] Add test cases or procedure
- [ ] Add PR label

### CODE REVIEW

**Comment by TokenHash** [comment]
Given MEW's volumes, Its important to migrate to a more trustworthy node service provider. If MEW can combine Ethercluster by adding running proprietary nodes, that would be even better.

**Comment by YazzyYaz** [comment]
@gamalielhere Readded the commonwealth nodes and added the two new nodes for ETC by Ethercluster

**Comment by YazzyYaz** [comment]
@gamalielhere is it good to go? We want to be able to provide Atlantis-compatible nodes for ETC since we have a fork in less than a week.

**Comment by YazzyYaz** [comment]
If you curl it via Terminal, using this command:
```sh
curl --data '{"method":"eth_getBlockByNumber","params":["0x0", false],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://www.ethercluster.com/etc
```

This is a command to get the `eth_getBlockByNumber` of the first block to the endpoint https://www.ethercluster.com/etc

The response to it is:
```sh
{"jsonrpc":"2.0","result":{"author":"0x0000000000000000000000000000000000000000","difficulty":"0x400000000","extraData":"0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa","gasLimit":"0x1388","gasUsed":"0x0","hash":"0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x0000000000000000000000000000000000000000","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000042","number":"0x0","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sealFields":["0xa00000000000000000000000000000000000000000000000000000000000000000","0x880000000000000042"],"sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x21c","stateRoot":"0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544","timestamp":"0x0","totalDifficulty":"0x400000000","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]},"id":1}
```

Which indicates the nodes are online.

Can you share your Postman options? Perhaps its a config issue?

**Comment by gamalielhere** [comment]
@YazzyYaz I'm sending a post call with this body:
```
{
	"jsonrpc":"2.0",
	"method":"net_version",
	"params": [],
	"id": 1
}
```

**Comment by YazzyYaz** [comment]
Yeah, this command works for me in Terminal:
```sh
curl --data '{"method":"net_version","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://www.ethercluster.com/etc
```

The response I get is:
```sh
{"jsonrpc":"2.0","result":"6","id":1}
```

**Comment by TokenHash** [comment]
The fork is happening on 11:54:14 am UTC  |  Thursday, September 12, 2019

That is in 3 days. We don't know whether "ETC Commonwealth" is malicious or not friendly. They have not responded to requests to confirm whether they are upgrading.

As MEW has such a large user base, it should at least have an honest alternative.

@gamalielhere @YazzyYaz it would be great if you guys could coordinate to set the nodes up on Ethercluster. It doesn't seem like rocket science.

**Comment by YazzyYaz** [comment]
@gamalielhere can you post your Postman config so we can help you debug it? It works fine via curl and other websites using the endpoint, perhaps your Postman config can help us identify the problem?

Also, any error response you get back on Postman can help us debug it further with you. Let us know.

**Comment by bobsummerwill** [comment]
Hey @kvhnuke and @gamalielhere!

Sorry for the nag, but this is getting to be pretty time-critical now, with the ETC Atlantis hardfork happening in two days time.   We really don't want any MEW users on ETC to have a bad experience.

Please do share whatever might help @YazzyYaz to resolve the troubleshooting of your Postman configuration.   This does seem like it is some minor config issue.   Our EtherCluster nodes are being used successfully in many different contexts.

Bob Summerwill, Executive Director, ETC Cooperative ❤️

**Comment by YazzyYaz** [comment]
Hey guys, moving to this PR: https://github.com/MyEtherWallet/MyEtherWallet/pull/1418 for this node: https://www.ethereumclassic.network RPC endpoint that's also owned by us while we fix up this PR for Ethercluster.

**Comment by YazzyYaz** [comment]
@gamalielhere can you please retry it with Postman and tell me if it works for https://www.ethercluster.com/etc ?

I found an SSL error that I had to fix and I tested it and it works. Please let me know if it works for you too!

**Comment by YazzyYaz** [comment]
@SteveMieskoski we are waiting on you for the final approval. Time is of the essence since we have a hardfork in less than 24 hours. Do you have any questions about this PR? Happy to answer anything. Best wishes.

**Comment by TokenHash** [comment]
It would be great if @SteveMieskoski could review this ASAP as the hadr fork is in less that 24 hs.

**Comment by kvhnuke** [comment]
This will be part of today's release, we are on schedule!

**Comment by YazzyYaz** [comment]
Thank you so much @kvhnuke!

**Pull request merged**
