### PR TITLE
feat: Add ETC Coop Node

### PR DESCRIPTION
**Pull request by YazzyYaz**
### Feature

- [ ] Updated CHANGELOG.md
- [*] Is this a user submitted feature request?
  - [ ] Link to issue: This is updating ETC RPC endpoints to use those of Ethercluster which is supported by Ethereum Classic Cooperative. Commonwealth doesn't do work on ETC anymore, they work on Calisto.
- [ ] Add test cases or procedure
- [ ] Add PR label

### CODE REVIEW

**Comment by YazzyYaz** [comment]
@gamalielhere can you please retry it with Postman and tell me if it works for https://www.ethercluster.com/etc ?

I found an SSL error that I had to fix and I tested it and it works. Please let me know if it works for you too!

**Comment by gamalielhere** [comment]
@YazzyYaz yeah it works. Will be merging this today or tomorrow

**Comment by YazzyYaz** [comment]
@SteveMieskoski we are waiting on you for the final approval. Time is of the essence since we have a hardfork in less than 24 hours. Do you have any questions about this PR? Happy to answer anything. Best wishes.

**Comment by TokenHash** [comment]
It would be great if @YazzyYaz @SteveMieskoski could review this ASAP as the hadr fork is in less that 24 hs.

**Pull request merged**
