### PR TITLE
Bitbox02 integration fix

### PR DESCRIPTION
**Pull request by Tomasvrba**
### Feature

Update bitbox api js to 0.4.0

### Bug

Re-add lost bitbox modals

### CODE REVIEW

**Comment by Tomasvrba** [comment]
@kvhnuke Please see commit message: https://github.com/MyEtherWallet/MyEtherWallet/pull/2163/commits/95ee18a768d2534aafb1480dcf00f4454577ad2b

Seems like the BitBox modals from my previous PR had been lost during refactoring of the AccessWalletLayout, so I'm re-adding them here.

Also updating the lib to the newly released 0.4.0 and firmware 7.0.0.
@SteveMieskoski To test, you can update to the newest firmware with the current 4.18.0 app: https://shiftcrypto.ch/start/

**Comment by Tomasvrba** [comment]
By the way, thank you @kvhnuke for fixing the store dispatch code in the previous PR. Clearing the wallet on device unplug now works great. 

Could I please get a comment from you on this related issue? https://github.com/MyEtherWallet/MyEtherWallet/issues/2052

Because currently with using clearWallet, I don't know how to make address switching work. Details are in the issue.

**Comment by kvhnuke** [comment]
Thanks @Tomasvrba for the fix, we will include this. PR significantly increased final build size and broke the travis build due to virustotal limitations. so we had to rebase the code to seperate it, that is probably when the we lost some of the code. Since then we made the build pass, but looking for other ways to reduce the final build size. We will include the PR in the release, however let us know if you know anyway to split the chunks more efficiently to reduce overall build size

**Comment by Tomasvrba** [comment]
> Thanks @Tomasvrba for the fix, we will include this. PR significantly increased final build size and broke the travis build due to virustotal limitations. so we had to rebase the code to seperate it, that is probably when the we lost some of the code. Since then we made the build pass, but looking for other ways to reduce the final build size. We will include the PR in the release, however let us know if you know anyway to split the chunks more efficiently to reduce overall build size

Great, thank you! Yeah, I mentioned the size to @SteveMieskoski in an email a while ago and also on the original PR. One way to address it on MEW side would be to split the large bitbox02-api dependency into a separate chunk with webpack instead of bundling all node_modules into a single `vendors` chunk as configure in `defaultConfigs.js`

```
  optimization: {
    splitChunks: {
      cacheGroups: {
        commons: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors',
          chunks: 'initial'
        }
      }
    }
}
```

This would then let us lazy-load the library only on demand when the user actually wants to use the BB02. 
I played around with this a little bit when doing the integration, but as mentioned on the original PR, I didn't want to mess with your configs before discussing this. 
Here are some references that I was using for dynamic webpack loading/vue lazy-loading:

https://webpack.js.org/guides/lazy-loading/
https://vuedose.tips/tips/dynamic-imports-in-vue-js-for-better-performance/
https://vueschool.io/articles/vuejs-tutorials/lazy-loading-individual-vue-components-and-prefetching/

Let me know if that's something you'd consider. 

On our side, we are also of course working on trying to optimize GopherJS to shrink the final size of the js library compiled from Go.

**Pull request merged**
