### PR TITLE
Add typescript support

### PR DESCRIPTION
**Pull request by theqp**
Add the feasibility of writing typescript code.

### CODE REVIEW

**Comment by theqp** [comment]
Closing due history rewrite.

**Review by gamalielhere — COMMENTED** [review]
What is the current issue and what does this PR solve?

**Comment by theqp** [comment]
@gamalielhere 
This gives developers the ability to add Typescript code to the codebase.
Typescript helps to preventing bugs like `Cannot read property 'toLowerCase' of undefined` (this is a current issue, I will open an issue for it)

**Comment by gamalielhere** [comment]
our upcoming iteration will be fully typescript supported as it will be developed with vue 3 in mind. closing this PR.

**Pull request closed without merging**
