### PR TITLE
Add SingularDTV derivation to mnemonic paths.

### PR DESCRIPTION
**Pull request by danbaragan**
SingularDTV used ConsenSys/eth-lightwallet's default derivation path of `m/0'/0'/0'` since spring of 2016, before `m/44'/60'/0'` getting a lot of traction. Many users have created SingularDTV lightwallets over the past 18 months, and it would help a lot if they could access their wallets directly from MEW without the need to enter the derivation path manually.

### CODE REVIEW

**Comment by tayvano** [comment]
PS: this was already updated on v3 a few days ago

**Comment by wbobeirne** [comment]
Code looks fine to me, but from a user perspective, is `SingularDTV` a label that everyone will get? Do we need to add ConsenSys or eth-lightwallet to the label to help other people?

**Comment by wbobeirne** [comment]
@dternyak perhaps this should make it into #849 finally?

**Comment by dternyak** [comment]
@wbobeirne Yes, thanks for the reminder. I'll make a note to include this in Part 2 of that PR.

**Comment by dternyak** [comment]
Fixed in https://github.com/MyEtherWallet/MyEtherWallet/pull/849/commits/5c813528153359d57108cdd684dcd184d3233654

@danbaragan I hope you won't mind that I didn't include your commit - it was easier for me to manually re-use your dPath value.

**Pull request closed without merging**
