### PR TITLE
Adding RSK networks

### LINKED ISSUE #290: Adding RSK network
**Feature Request**
- Addition of RSK Mainnet network configuration
- Addition of RSK Testnet network configuration
- Fix of derivation path default option (depending on selected network)

### PR DESCRIPTION
**Pull request by herrerameri**
### Feature
- [x] Is this a user submitted bug/feature?
  - [x] Link to issue:  It closes #290

### CODE REVIEW

**Comment by SteveMieskoski** [comment]
Hi @herrerameri  , please resolve the conflicts. Thanks.

**Comment by herrerameri** [comment]
@SteveMieskoski done!

**Comment by herrerameri** [comment]
@kvhnuke done! Please let me know if I forgot sth more!
Thanks!

**Comment by herrerameri** [comment]
@gamalielhere done!

**Pull request merged**
