### PR TITLE
BitBox02 naming and fix attestation failure warning

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by kvhnuke** [comment]
hi @benma are you affiliated with bitbox? if so can you contact us. We are trying to integrate bitbox 1 to v6 however we dont have a bitbox 1 for testing

**Comment by benma** [comment]
@kvhnuke yes, I work for Shift. I'll get back to you about the BitBox 1 within a few days.

This PR however is about the BitBox02 (independent of BitBox 1).

**Comment by kvhnuke** [comment]
> @kvhnuke yes, I work for Shift. I'll get back to you about the BitBox 1 within a few days.
> 
> This PR however is about the BitBox02 (independent of BitBox 1).

you can contact me @kvhnuke on telegram

**Comment by benma** [comment]
@kvhnuke could you please check this PR again and merge it? The change is minimal. Thanks.

**Review by gamalielhere — APPROVED** [review]

**Comment by benma** [comment]
> @benma can you add an entry to `./changelog`?

Done

**Review by rsteubs — APPROVED** [review]

**Comment by gamalielhere** [comment]
Added into #3442

**Pull request closed without merging**
