### PR TITLE
[Feature] On transaction send UTF-8 data

### PR DESCRIPTION
**Pull request by theqp**

### CODE REVIEW

**Comment by theqp** [comment]
Closing due history rewrite.

**Comment by gamalielhere** [comment]
What is the current issue and what does this PR solve?

**Comment by theqp** [comment]
> What is the current issue and what does this PR solve?

This is a new feature, adds the ability to send a text on transactions encoded as UTF-8.
image

**Comment by gamalielhere** [comment]
@theqp what's the purpose of utf data?

**Comment by theqp** [comment]
@gamalielhere The sender can provide a message in the transaction, like at banks. It is so common the Etherscan explorer can show transaction data as text
image

**Comment by kvhnuke** [comment]
I know this can be an additional feature but not technical if users want to send utf they can use a ascii to hex converter. I don't believe this is needed and I'm closing this PR. Feel free to make other PRs

**Pull request closed without merging**
