### PR TITLE
Hide menu options that are not available for the selected network

### PR DESCRIPTION
**Pull request by alepc253**
### Feature

- [ ] Updated CHANGELOG.md
- [x] Is this a user submitted feature request?
  - [x] Link to issue: [#451](https://github.com/MyEtherWallet/MyEtherWallet/issues/451)
- [ ] Add test cases or procedure
- [x] Add PR label

### CODE REVIEW

**Comment by kvhnuke** [comment]
This is great! Thanks. What do you think about doing it the opposite way, for example each network will have supported tabs! since some networks might support some dapps not others
```
ETH:{
         supported: {
                    dapps: ["ens", "ens-subdomain"], 
                    send: ["send-online","send-offline"]
                    ...etc
         }
}
```

**Comment by alepc253** [comment]
I think now we have a better solution, we can set supported menu **and** children menu tabs (and, as before, if you don't set this setting in the network configuration, everything is shown).
About dapps, they are not built as tabs so it should be managed with another setting.

**Comment by alepc253** [comment]
@kvhnuke any news about this?

**Comment by kvhnuke** [comment]
we are integrating this in one of our PRs Thanks!

**Pull request closed without merging**
