### PR TITLE
Dev/mew decision tree new

### PR DESCRIPTION
**Pull request by hsurf22**
### Feature

- [x] Updated CHANGELOG.md
- [x] Add PR label
  - Add decision tree

https://www.youtube.com/watch?v=U4tEnBwLbc0&feature=youtu.be

Screenshot from 2019-09-18 21-26-52

### CODE REVIEW

**Comment by SteveMieskoski** [comment]
Also, noticed the 'house' home icon on the bottom has hover effects, but doesn't have a click event. (does not do anything when clicked)

**Comment by hsurf22** [comment]
> This should probably show in all pages, not just the home page.

Yes. I think this is showing on all other pages.
I just tested it and works on all pages.

**Comment by hsurf22** [comment]
> Also, noticed the 'house' home icon on the bottom has hover effects, but doesn't have a click event. (does not do anything when clicked)

This button brings user to the very top of the decision tree category.
Now home button is hidden when user is on top category, so users can't see the button.

**Comment by hsurf22** [comment]
Markup data has been updated
and some design changes have been made.

**Pull request merged**
